config/routes.rb
Rails.application.routes.draw do
  resources :charges
  devise_for :users
  resources :causes

  root to: 'home#index'

end

app/views/causes/_form.html.haml
= simple_form_for(@cause) do |f|
  = f.error_notification

  = f.input :title
  = f.input :description
  = f.input :total
  = f.input :members
  = f.input :user_id

  = f.button :submit, :class => 'btn btn-primary'

  - if @cause.persisted?
    = link_to 'Cancel', @cause, :class => 'btn btn-default'
  - else
    = link_to 'Cancel', causes_path, :class => 'btn btn-default'

  - if can?(:destroy, @cause) && @cause.persisted?
    = link_to @cause,
        :class => 'btn btn-danger pull-right',
        :method => :delete,
        :data => { :confirm => 'Are you sure?' } do
      = fa_icon 'trash-o'
      = "Destroy #{Cause.model_name.human}"

app/views/causes/edit.html.haml
- content_for :breadcrumbs do
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    %li= link_to Cause.model_name.human.pluralize, causes_path
    %li= link_to Cause.model_name.human, @cause
    %li.active Edit

.container
  .page-header
    %h1= "Edit #{Cause.model_name.human}"

  = render 'form'

app/views/causes/index.html.haml
- content_for :breadcrumbs do
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    %li.active= Cause.model_name.human.pluralize

.container
  .page-header.clearfix
    %h1.pull-left= Cause.model_name.human.pluralize
    .pull-right{ :style => 'margin-top: 20px' }
      - if can?(:new, @causes.new)
        = link_to new_cause_path, :class => 'btn btn-success pull-right' do
          = fa_icon 'plus-circle'
          = "New #{Cause.model_name.human}"

  %table.table.table-hover.table-striped
    %thead
      %tr
        %th= Cause.human_attribute_name(:title)
        %th= Cause.human_attribute_name(:description)
        %th= Cause.human_attribute_name(:total)
        %th= Cause.human_attribute_name(:members)
        %th= Cause.human_attribute_name(:user_id)
        %th
        %th
        %th

    %tbody
      - @causes.each do |cause|
        %tr
          %td= cause.title
          %td= cause.description
          %td= cause.total
          %td= cause.members
          %td= cause.user_id
          - if can?(:show, cause)
            %td= link_to 'Show', cause
          - if can?(:edit, cause)
            %td= link_to 'Edit', edit_cause_path(cause)
          - if can?(:destroy, cause)
            %td= link_to 'Destroy', cause, :method => :delete, :data => { :confirm => 'Are you sure?' }

  = paginate @causes

app/views/causes/new.html.haml
- content_for :breadcrumbs do
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    %li= link_to Cause.model_name.human.pluralize, causes_path
    %li.active New

.container
  .page-header
    %h1= "New #{Cause.model_name.human}"

  = render 'form'

app/views/causes/show.html.haml
- content_for :breadcrumbs do
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    %li= link_to Cause.model_name.human.pluralize, causes_path
    %li.active= Cause.model_name.human

.container
  .page-header.clearfix
    %h1.pull-left= Cause.model_name.human
    .pull-right{ :style => 'margin-top: 20px' }
      - if can?(:edit, @cause)
        = link_to edit_cause_path(@cause), :class => 'btn btn-default pull-right' do
          = fa_icon 'edit'
          = "Edit #{Cause.model_name.human}"

  %dl.dl-horizontal
    %dt= Cause.human_attribute_name(:title)
    %dd= @cause.title
    %dt= Cause.human_attribute_name(:description)
    %dd= @cause.description
    %dt= Cause.human_attribute_name(:total)
    %dd= @cause.total
    %dt= Cause.human_attribute_name(:members)
    %dd= @cause.members
    %dt= Cause.human_attribute_name(:user_id)
    %dd= @cause.user_id