config/routes.rb
Rails.application.routes.draw do
  resources :charges
  devise_for :users
  resources :causes

  root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <title>IdeaJump</title>

    <!-- Bootstrap core CSS -->
  <!--   <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js">
 -->
    <!-- Add custom CSS here -->
   <!--  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css"> -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body>

  <%= yield %>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = display_meta_tags :site => 'JumpStart', :reverse => true, :separator => '-'
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    %navbar.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{ :type => 'button', :data => { :toggle => 'collapse', :target => '#bs-example-navbar-collapse-1' }}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          = link_to 'Zangetsu', root_path, :class => 'navbar-brand'

        .collapse.navbar-collapse{ :id => 'bs-example-navbar-collapse-1' }
          %ul.nav.navbar-nav
            / primary navigation

          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle{ :href => '#', :data => { :toggle => 'dropdown' }}
                  = gravatar_image_tag(current_user.email,
                      :alt => current_user.username,
                      :class => 'avatar',
                      :gravatar => { :filetype => 'png',
                                     :size => 32 })
                  = truncate current_user.username
                  %b.caret

                %ul.dropdown-menu
                  %li
                    = link_to edit_registration_path(current_user) do
                      = fa_icon 'user'
                      = "Edit #{User.model_name.human}"
                  %li.divider
                  %li
                    = link_to destroy_user_session_path, :method => :delete do
                      = fa_icon 'sign-in'
                      Sign out
            - else
              %li
                = link_to new_user_session_path do
                  = fa_icon 'sign-out'
                  Sign in

    .container
      = yield :breadcrumbs
      = bootstrap_flash

    = yield